name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - production

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::562775231936:role/www.masaru-study.com-deploy-role
          aws-region: ap-northeast-1

      # - name: Debug OIDC token
      #   run: |
      #     echo "== Requesting OIDC token =="
      #     TOKEN=$(curl -sSL -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
      #       "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
      #       | jq -r '.value')
      #     echo "${TOKEN}" | cut -d. -f2 | base64 -d | jq .

      - name: Sync files to S3
        run: aws s3 sync public/ s3://www.masaru-study.com/ --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E252XUYLGIKS54 \
            --paths "/*"
